import { Resolvers } from "~/services/gql/gql-types"; // auto-generated by graphql-codegen script
import { Context } from "~/services/gql/context";
import { SaveResult } from "../gql/gql-types";
import { PractitionerService } from "./practitioner-service";

export const resolvers: Resolvers = {
  Query: {},
  Mutation: {
    // addPractitioner: async (
    //   parent,
    //   args: MutationSavePractitionerArgs,
    //   context: Context
    // ): Promise<SaveResult> => {
    //   const result = await PractitionerService.create(context, args.practitioner);
    //   return {
    //     error:
    //       result.modifiedCount !== 1 ? "Failed to save practitioner" : null,
    //   };
    // },
  },
};
