import { MutationAddSiteArgs, Resolvers } from "~/services/gql/gql-types"; // auto-generated by graphql-codegen script
import { SiteService } from "./site-service";

export const resolvers: Resolvers = {
  Query: {},
  Mutation: {
    // addSite: async (parent, args: MutationAddSiteArgs, context) => {
    //   SiteService.create(args.site);
    //   return null;
    // },
    updateSite: async (parent, args, context) => {
      SiteService.updateTitle(args.site.siteId, args.site.title);
      return undefined;
    },
  },
};
