import { Resolvers } from "~/services/gql/gql-types"; // auto-generated by graphql-codegen script
// import {
//   getFile,
//   insertNewFileForUpload,
//   prepareFileDownload,
// } from "./file-service";

export const resolvers: Resolvers = {
  Mutation: {
    // prepareFileDownload: async (_parent, args, context) => {
    //   const file = await getFile(args.fileInfo._id);
    //   if (file) {
    //     return prepareFileDownload(file);
    //   } else {
    //     return {
    //       error: {
    //         code: "NOT_FOUND",
    //         message: "File not found",
    //       },
    //     };
    //   }
    // },
    // prepareFileUpload: async (_parent, args, context) => {
    //   return await insertNewFileForUpload(args.fileInfo);
    // },
  },
};
