import { Resolvers } from "~/services/gql/gql-types"; // auto-generated by graphql-codegen script
import {} from "./task-service";

export const resolvers: Resolvers = {
  Query: {},
  Mutation: {},
};
