import { MutationSendSmsArgs, Resolvers } from "~/services/gql/gql-types"; // auto-generated by graphql-codegen script
import { Context } from "../gql/context";

import { sendSms } from "./sms-service";

export const resolvers: Resolvers = {
  Mutation: {
    sendSms: async (parent, args: MutationSendSmsArgs, context: Context) => {
      sendSms(args.params);
      return {};
    },
  },
};
